import Head from "next/head";
import Navbar from "../components/Navbar";
import Main from "../components/Main";
import About from "../components/About";
import WhatIDo from "../components/WhatIDo";
import Skills from "../components/Skills";
import Work from "../components/Work";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import { useState } from "react";
import Sidebar from "../components/Sidebar";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    return setIsOpen(!isOpen);
  };

  return (
    <>
      <Head>
        <title>Afraz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar toggleSidebar={toggleSidebar} />
      </header>
      <main>
        <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar} />
        <Main />
        <About />
        <WhatIDo />
        <Skills />
        <Work />
        <Contact />
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
